# -*- coding: utf-8 -*-
"""HW_CallAPI_Public

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aZpEDHPtb-0e4bwRGICXZTC6N4d7Jlzg
"""

## import module
from requests import get
from time import sleep
import pandas as pd
import csv
#url = "https://api.genderize.io/?name=luc"
#url for predicting the gender of a person based on their name(Genderize.io)
url = "https://api.genderize.io/?name="
da_gender = {
    "count":[],
    "name":[],
    "gender":[],
    "probability":[]
}
df1 = pd.DataFrame(da_gender)
response = get(url)
## 200 = OK
print (response.status_code)

## see data that get back from server
try:
    Flag_loop = True
    col_name = ["count","name","gender","probability"]
    while (Flag_loop):
            Input_name = input ("Please enter your name (Q=quit) : ")
            if (Input_name.upper() != "Q"):
                new_url = url  + Input_name
                print(new_url)
                resp = get(new_url).json()
                temp_df = pd.DataFrame({
                    "count": [resp["count"]],
                    "name": [resp["name"]],
                    "gender": [resp["gender"]],
                    "probability": [resp["probability"]],
                })
                df1 = pd.concat([df1, temp_df], ignore_index=True)
            else:
                Flag_loop = False
    print(df1)
    with open ("gender.csv","w") as file:
            writer = csv.DictWriter(file,fieldnames = col_name)
            writer.writeheader()
            writer.writerows(df1.to_dict(orient='records'))
            file.close()
except:
    print ("Any Error")

!dir

!cat gender.csv

